[package]
name = "microchip-rs"
version = "0.1.0"
authors = ["Florent Uguet <florent.uguet@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
incremental = false
codegen-units = 1

[dev-dependencies]
criterion = "0.7.0"

[dependencies]
rustyline = "17.0.1"

[[bench]]
name = "bench"
harness = false

[lib]
name = "microchip_rs"
path = "src/lib/mod.rs"
bench = false

[[bin]]
name = "microchip_rs_bin"
path = "src/bin/main.rs"
bench = false
